version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: gungun
      POSTGRES_PASSWORD: gunguin123
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://gungun:gungun123@db:5432/chatdb
      SECRET: "supersecretkey"
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db", "python", "application.py"]  

