apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flask-postgres.fullname" . }}-pvc
  labels:
    {{- include "flask-postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.primary.persistence.size }}
  {{- if .Values.postgresql.primary.persistence.storageClassName }}
  storageClassName: {{ .Values.postgresql.primary.persistence.storageClassName }}
  {{- end }}