apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-postgres.fullname" . }}-secret
  labels:
    {{- include "flask-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  secret-key: {{ .Values.secrets.secretKey | quote }}
  db-password: {{ .Values.postgresql.auth.password | quote }}